export { default as Machadotwin } from "./Fins/machadotwinfin.webp";
export { default as Captainfin } from "./Fins/tyler-warren-especia.webp";
export { default as Futuresjordy } from "./Fins/futuresjordysmith.webp";
export { default as Fcsfanning } from "./Fins/fcs2mickfanning.webp";
export { default as Wavebackground } from "./Background/wave.jpg";
export { default as Fcskeel } from "./Fins/fcs-ii-retro-keel-fin.webp";
export { default as Fatboy } from "./Fins/fat-boy-fin-8inch.webp";
export { default as Blackstix } from "./Fins/futures_machado_pivot_blackstix.webp";
export { default as Logo } from "./logo/logo.png";
